// <auto-generated />
using System;
using DutchApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DutchApp.Migrations
{
    [DbContext(typeof(DutchContext))]
    [Migration("20181130095453_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DutchApp.Data.Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AuxiliaryVerbId");

                    b.Property<string>("FirstPersonPlural");

                    b.Property<string>("FirstPersonSingular");

                    b.Property<string>("InfinitiveEN");

                    b.Property<string>("InfinitiveNL");

                    b.Property<string>("PastParticiple");

                    b.Property<string>("SecondPersonSingular");

                    b.Property<string>("SimplePastPlural");

                    b.Property<string>("SimplePastSingular");

                    b.Property<string>("ThirdPersonSingular");

                    b.HasKey("Id");

                    b.HasIndex("AuxiliaryVerbId");

                    b.ToTable("Verbs");
                });

            modelBuilder.Entity("DutchApp.Data.Verb", b =>
                {
                    b.HasOne("DutchApp.Data.Verb", "AuxiliaryVerb")
                        .WithMany()
                        .HasForeignKey("AuxiliaryVerbId");
                });
#pragma warning restore 612, 618
        }
    }
}
